---
- include_vars:
    file: defaults/main.yml
- ec2_vpc_subnet:
    state: present
    vpc_id: "{{ vpc.vpc.id }}"
    cidr: "{{ subnet_cidr }}"
    resource_tags:
      Name: "{{ name }}"
    region: "{{ region }}"
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
  register: subnet
  
- name: print
  debug:
    msg: "{{ subnet.subnet.id }}"  
