# Creates a EC2 Instance
# Parameters:
# instanceType: Type of the instance (Refer to AWS EC2 site for types)
# name: name
# image: Image name
# group_id: ID of security group
# count: Number of instances
# region: EC2 region
# subnet: VPC Subnet
# instance-id: Instance ID
---
- include_vars:
    file: defaults/main.yml

- ec2:
    key_name: "{{ aws_keypair_name }}"
    image: "{{ image | default('ami-8ca83fec') }}"
    instance_type: "{{ instance_type | default('t2.micro') }}"
    region: "{{ region | default('us-west-2') }}"
    wait: yes
    group_id: "{{ securityGroup.group_id }}"
    count: "{{ count | default(1) }}"        
    tenancy: "{{ tenancy | default('default') }}"
    vpc_subnet_id: "{{ subnet.subnet.id }}"
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    assign_public_ip: yes
    
  register: ec2

- name: Print
  debug:
    msg: "{{ ec2.instances }}"

    